### ISSUE TITLE
Create website design Wireframe

### ISSUE THREAD

**Issue by JakubPonulak** [JakubPonulak/5_hackers#4]
Design and label wireframe which shows the planned basic layout of our website.

[Link](https://www.canva.com/design/DAEwHOgoljU/OX48O2_6XNpenzuNlGQnnA/view?utm_content=DAEwHOgoljU&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton)

**Comment by SreejaVad** [comment]
[Wireframe Link](https://www.canva.com/design/DAEwHOgoljU/OX48O2_6XNpenzuNlGQnnA/view?utm_content=DAEwHOgoljU&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton)
