### ISSUE TITLE
Week 11 Review Ticket - Jakub P

### ISSUE THREAD

**Issue by JakubPonulak** [JakubPonulak/5_hackers#64]
# Self Evaluation: 9.2/10
# Crossover Grading (Paul D.): 9.6/10
**Individual Create Task Projects**
[Create Task: Jakub](https://github.com/JakubPonulak/5_hackers/wiki/Create-Task:-Jakub)
**Team Final Grading Considerations**
[PBL Theme](https://jakubponulak.github.io/5_hackers/)
Sassy/Bootstrap: [style.scss](https://github.com/JakubPonulak/5_hackers/blob/main/static/style/style.scss), [base.html](https://github.com/JakubPonulak/5_hackers/blob/main/templates/layouts/base.html), [bootstrapLayouts.html](https://github.com/JakubPonulak/5_hackers/blob/main/templates/bootstrapLayouts.html)
Blueprints: [main.py](https://github.com/JakubPonulak/5_hackers/blob/main/main.py), [__init__.py](https://github.com/JakubPonulak/5_hackers/blob/main/class_topics/__init__.py)
[CRUD](https://github.com/JakubPonulak/5_hackers/tree/main/crud)
[MVC Feature](https://github.com/JakubPonulak/5_hackers/blob/main/templates/main_page.html)
[Runtime Features Video](https://drive.google.com/file/d/1OyVfDc0skdZpc7wTEDjLu1oY6qP3cCMJ/view?usp=sharing)

**Self Evaluation: 9.2/10**
Create Task: 5/5
The wiki page I created for my create task includes explantions about my project and how to use it (included in the responses). My program takes an input, uses a list, includes at least one procedure, one algorithm, has calls in HTML and has instructions for output (all the CB requirements). The feature fully works on the website, is commited to GitHub, and all the written responses are completed thoroughly. The video is under 1 minute, uses subtitles, and meets all the CB requirements.

PBL Github pages. Jekyll, WIKI, live review focus: 0.9/1
The theme of our website is described in our wiki and Jekyll page. We have several examples of Sassy and Bootstrap in our project, though I think we could add a bit more. New blueprints were added for "Class Topics", but we could have added some more. CRUD operations work as expected, and my MVC feature (search bar), which uses JS algorithms, is commited.

Runtime Video: 0.9/1
The video shows all the important aspects of our project, including our best features, CRUD operations, and MVC usage (in this case the search bar on the main page). The video also shows Google Translate on our website, and displays/explains our team Scrum Board. The video could have been a bit shorter.

Clarity and Quality of finding Info: 0.9/1
Our website is pretty well organized, and easy to navigate. None of the UI is messy or unorganized, and the colors/theme allow clear visibility. Other aspects of our project, such as our GitHub wiki or Jekyll pages could be more organized, but they are somewhat organized. 

Deployed Project: 0.5/1
Our deployment worked part of the time, as we had problems with one of our team member's Raspberry Pi. While the website was not deployed 24/7, we had the ability to deploy it some of the time.

N@TM Readiness: 0.9/1
Our website is ready for presentation during N@TM. Everyone in my team plans on participating, and has a specific topic/feature that they will talk about, along with helping in the general presentation. Our website is not currently deployed, so we need to make sure that happens.

**Comment by Paul-D6** [comment]
## Paul Evaluation
Pair Evaluation(Paul): 9.6/10
Create Task: 5/5
Create task meets all the requirements. Wiki page.is fully complete and the video. shows the functionality of the Create Task.  Idea contributes to the purpose of their website. Program is done in Javascript.

PBL Github pages. Jekyll, WIKI, live review focus 1/1
Sassy/bootstrap is used and in project. Blue prints are there for organization. Crud is operational and MVC is used properly for various functions
Runtime Features shown in 1 min video .9/1
Video shows all features on video along with google translate. Scrum looks neat and organized. Crud is functional although it does not contribute to the purpose of the website. Blue prints are there but there could be more to make main.py organized.
Clarity and quality of finding information
Website is well organized and so is their Github. Scrum board complete which makes their process easy to follow. 
Deployed Project 24/7 - Deployment Overview and Policies in Github Pages .7/1
Deployed website is not up all the time and fully functional
[N@tM](mailto:N@tM) Participation and readiness for event 1/1
Their website is complete and they are ready to present their individual parts of their PBL

College Board quizzes done along with the Final Exam. Corrections are there to show full understanding of college board criteria
